options:
  debug:
    type: string
    default: "True"
    description: "enable debug"
  midonet_puppet_modules:
    type: string
    default: "https://github.com/midonet/orizuru.git"
    description: "Repository for zoo-keeper"
  midonet_puppet_modules_branch:
    type: string
    default: "master" 
    description: "Branch on Repository"
  username:
    type: string
    default: "calsoft" 
    description: "username for midonet repository"
  password:
    type: string
    default: "HJu7S6DFq" 
    description: "password for the midonet repository"
  midonet_flavor:
    type: string
    default: "MEM" 
    description: "midonet flavor for repository"
  midonet_version:
    type: string
    default: "1.8" 
    description: "midonet version for repository"
  midonet_openstack_plugin_version:
    type: string
    default: "juno" 
    description: "openstack release version"
  os_release:
    type: string
    default: "trusty" 
    description: "ubuntu os release"

